### ISSUE TITLE
Getting a fatal error upon saving/editing users

### ISSUE THREAD

**Issue by TomDeSmet** [lindseydiloreto/craft-autoassignusergroup#4]
When I change a username I get this error allthough the new username is saved.

`Fatal error: Using $this when not in object context in /.../craft/plugins/autoassignusergroup/AutoAssignUserGroupPlugin.php on line 13`

I also get this when adding new users for example.

**Comment by lindseydiloreto** [comment]
Thanks for the heads up! I'll take a look into it, and at least note the requirements in the README.
